server:
  port: 8080
# 配置真实数据源
spring:
  shardingsphere:
    #数据源配置
    datasource:
      names: ds0,ds1
      # 配置第 1 个数据源
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demodb
        username: root
        password: 123456
      # 配置第 2 个数据源
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3307/demodb
        username: root
        password: 123456
##    rules:
#      sharding:

#        # 配置分片规则
#        tables:

    props:
      sql.show: true  #打印sql:
#    rules:
#      sharding:
#        tables:
#          # 配置 t_order 表规则
#          order:
#            actual-data-nodes: ds$->{0..1}.order$->{0..15}
#            # 配置分库策略
#            database-strategy:
#              standard:
#                sharding-column: user_id
#                sharding-algorithm-name: database_inline
#            # 配置分表策略
#            table-strategy:
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: table_inline
#            # 配置分片算法
#        shardingAlgorithms:
#          database_inline:
#            type: INLINE
#            props:
#              algorithm-expression: ds$->{user_id % 2}
#          table_inline:
#            type: INLINE
#            props:
#              algorithm-expression: order$->{id % 15}
##根据年龄分库
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 2}
#根据id分表
        tables:
          order:
            actual-data-nodes: ds$->{0..1}.order->{0..15}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: order->{id % 15}





#mybatis:
#    mapper-locations: classpath*:mapper/*.xml
#
#    #注意：对应实体类的路径
#    type-aliases-package: com.chenxk.sharding.demo2.mybatis.domain
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #配置文件引入
  config-location: classpath*:mybatis-config.xml
  type-aliases-package: com.chenxk.sharding.demo2.generator.domain
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    jdbc: #OFF
      sqltiming: error
      resultsettable: error
  config: classpath:logback-spring.xml
  file:
    path: D:/logs